name: PVN3D
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - at-spi2-atk=2.32.0=h1369247_0
  - at-spi2-core=2.35.1=h1369247_0
  - atk=2.36.0=0
  - atk-1.0=2.36.0=haf93ef1_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.11.5=py36he75722e_1
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - epoxy=1.5.4=h516909a_1
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=he06d7ca_0
  - fribidi=1.0.9=h516909a_0
  - future=0.18.2=py36_1
  - gdk-pixbuf=2.38.2=h3f25603_4
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.65.0=h6f030ca_0
  - gobject-introspection=1.64.1=py36h6d43c07_1
  - graphite2=1.3.13=he1b5a44_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gtk3=3.24.21=h45fd312_0
  - h5py=2.10.0=py36h7918eee_0
  - harfbuzz=2.4.0=h37c48d4_1
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - hicolor-icon-theme=0.17=0
  - icu=58.2=hf484d3e_1000
  - ipython=7.16.1=py36h95af2a2_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.1=py36h9f0ad1d_0
  - jpeg=9d=h516909a_0
  - kiwisolver=1.2.0=py36hdb11119_0
  - krb5=1.17.1=hfafb76e_1
  - ld_impl_linux-64=2.34=h53a641e_5
  - libcups=2.2.12=hf10b501_1
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_1
  - markupsafe=1.1.1=py36h8c4c3a4_1
  - matplotlib=3.0.2=py36h5429711_0
  - mistune=0.8.4=py36h8c4c3a4_1001
  - mkl=2019.5=281
  - mkl-service=2.3.0=py36h516909a_0
  - mkl_fft=1.1.0=py36hc1659b7_1
  - mkl_random=1.1.0=py36hb3f55d8_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.0=hc9558a2_0
  - nose=1.3.7=py36h9f0ad1d_1004
  - numpy-base=1.18.5=py36hde5b4d6_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - pango=1.42.4=h7062337_4
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pillow=7.1.2=py36hb39fc2d_0
  - pip=20.1.1=py_1
  - pixman=0.38.0=h516909a_1003
  - prompt-toolkit=3.0.5=py_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py36hcca6a23_4
  - python=3.6.10=hcf32534_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.0.1=py3.6_cuda10.0.130_cudnn7.4.2_2
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py36h7b6447c_0
  - qt=5.9.7=h52cfd70_2
  - readline=8.0=h7b6447c_0
  - scipy=1.2.1=py36h7c811a0_0
  - setuptools=39.1.0=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.32.3=h62c20be_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.2.2=py_3
  - tornado=6.0.4=py36h8c4c3a4_1
  - tqdm=4.46.1=py_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - wcwidth=0.2.5=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - attrs==19.3.0
    - bleach==3.1.5
    - common==0.1.2
    - cython==0.29.20
    - defusedxml==0.6.0
    - entrypoints==0.3
    - importlib-metadata==1.7.0
    - ipykernel==5.3.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jinja2==2.11.2
    - joblib==0.15.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.5
    - jupyter-core==4.6.3
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - notebook==6.0.3
    - numpy==1.18.5
    - open3d==0.9.0.0
    - opencv-python==4.2.0.34
    - packaging==20.4
    - pandocfilters==1.4.2
    - plyfile==0.7.2
    - prometheus-client==0.8.0
    - pyrsistent==0.16.0
    - pyzmq==19.0.1
    - scikit-learn==0.23.1
    - send2trash==1.5.0
    - sklearn==0.0
    - terminado==0.8.3
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.1.0
prefix: /home/yumi/anaconda3/envs/PVN3D

